#!/usr/bin/env bash
# Changes localhost to resolve to 127.0.0.2
# Changes facebook.com to resolve to 8.8.8.8

sed -i 's/127.0.0.1\tlocalhost/127.0.0.2\tlocalhost/' /etc/hosts
echo "8.8.8.8 facebook.com" >> /etc/hosts
