#!/usr/bin/env bash
# Configures localhost to resolve to 127.0.0.2 and facebook.com to 8.8.8.8
cp /etc/hosts /tmp/hosts
sed -i 's/127.0.0.1\tlocalhost/127.0.0.2\tlocalhost/' /tmp/hosts
echo "8.8.8.8 facebook.com" >> /tmp/hosts
echo "127.0.0.1 $(hostname)" >> /tmp/hosts
cp /tmp/hosts /etc/hosts
